from .event_views import (
    SanitaryEventCreateView,
    SanitaryEventDeleteView,
    SanitaryEventDetailView,
    SanitaryEventHardDeleteView,
    SanitaryEventListView,
    SanitaryEventRestoreView,
    SanitaryEventTrashListView,
    SanitaryEventUpdateView,
)
from .medication_views import (
    MedicationCreateView,
    MedicationDeleteView,
    MedicationListView,
    MedicationPermanentDeleteView,
    MedicationRestoreView,
    MedicationTrashListView,
    MedicationUpdateView,
)
from .protocol_views import (
    ProtocolApplyView,
    ProtocolCreateView,
    ProtocolDeleteView,
    ProtocolDetailView,
    ProtocolHardDeleteView,
    ProtocolListView,
    ProtocolRestoreView,
    ProtocolTrashListView,
    ProtocolUpdateView,
)

__all__ = [
    "SanitaryEventCreateView",
    "SanitaryEventDeleteView",
    "SanitaryEventDetailView",
    "SanitaryEventHardDeleteView",
    "SanitaryEventListView",
    "SanitaryEventRestoreView",
    "SanitaryEventTrashListView",
    "SanitaryEventUpdateView",
    "MedicationCreateView",
    "MedicationDeleteView",
    "MedicationListView",
    "MedicationPermanentDeleteView",
    "MedicationRestoreView",
    "MedicationTrashListView",
    "MedicationUpdateView",
    "ProtocolCreateView",
    "ProtocolDetailView",
    "ProtocolListView",
    "ProtocolUpdateView",
    "ProtocolDeleteView",
    "ProtocolTrashListView",
    "ProtocolRestoreView",
    "ProtocolHardDeleteView",
    "ProtocolApplyView",
]
