# Generated by Django 5.2.9 on 2025-12-09 01:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cattle", "0003_cattle_dam_cattle_dam_external_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "medication_type",
                    models.CharField(
                        choices=[
                            ("VACCINE", "Vaccine"),
                            ("ANTIBIOTIC", "Antibiotic"),
                            ("VERMIFUGE", "Vermifuge/Dewormer"),
                            ("SUPPLEMENT", "Supplement/Vitamin"),
                            ("HORMONE", "Hormone"),
                            ("EXAM", "Exam/Diagnosis"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("ML", "Milliliters (ml)"),
                            ("DOSE", "Doses"),
                            ("GRAM", "Grams (g)"),
                            ("MG", "Milligrams (mg)"),
                            ("PILL", "Pills/Tablets"),
                            ("UNIT", "Units"),
                        ],
                        default="ML",
                        max_length=10,
                        verbose_name="Unit",
                    ),
                ),
                (
                    "withdrawal_period_days",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Days after application before the animal can be slaughtered.",
                        verbose_name="Withdrawal Period (Days)",
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Manufacturer"
                    ),
                ),
                (
                    "active_ingredient",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Active Ingredient"
                    ),
                ),
                (
                    "default_dose",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Standard dose amount per animal",
                        max_digits=8,
                        null=True,
                        verbose_name="Default Dose",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medication",
                "verbose_name_plural": "Medications",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SanitaryEvent",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("date", models.DateField(verbose_name="Date of Event")),
                ("title", models.CharField(max_length=150, verbose_name="Event Title")),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Notes/Observation"),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Total Event Cost",
                    ),
                ),
                (
                    "medication",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="health.medication",
                        verbose_name="Medication/Product",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sanitary_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Performed By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sanitary Event",
                "verbose_name_plural": "Sanitary Events",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SanitaryEventTarget",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "applied_dose",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Applied Dose",
                    ),
                ),
                (
                    "cost_per_head",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Cost per Head",
                    ),
                ),
                (
                    "observation",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Observation"
                    ),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_records",
                        to="cattle.cattle",
                        verbose_name="Animal",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="health.sanitaryevent",
                        verbose_name="Event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sanitary Event Target",
                "verbose_name_plural": "Sanitary Event Targets",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_deleted", False)),
                        fields=("event", "animal"),
                        name="unique_animal_per_event",
                    )
                ],
            },
        ),
    ]
