# Generated by Django 5.2.9 on 2025-12-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medication",
            name="withdrawal_period_days",
        ),
        migrations.AddField(
            model_name="medication",
            name="batch_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Batch Number"
            ),
        ),
        migrations.AddField(
            model_name="medication",
            name="expiration_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Expiration Date"
            ),
        ),
        migrations.AddField(
            model_name="medication",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AddField(
            model_name="medication",
            name="withdrawal_days_meat",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Days until safe for slaughter.",
                verbose_name="Withdrawal (Meat)",
            ),
        ),
        migrations.AddField(
            model_name="medication",
            name="withdrawal_days_milk",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Days until milk is safe.",
                verbose_name="Withdrawal (Milk)",
            ),
        ),
    ]
