# Generated by Django 5.2.9 on 2025-12-10 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0002_remove_medication_withdrawal_period_days_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="sanitaryevent",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_performed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Performed By",
            ),
        ),
    ]
