# Generated by Django 5.2.9 on 2025-12-15 04:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0003_alter_sanitaryevent_performed_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthProtocol",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Health Protocol",
                "verbose_name_plural": "Health Protocols",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProtocolItem",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "default_dosage",
                    models.CharField(
                        help_text="E.g., 5ml, 1 dose, 10mg/kg",
                        max_length=50,
                        verbose_name="Default Dosage",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        help_text="E.g., Subcutaneous, Left side of neck",
                        max_length=255,
                        verbose_name="Notes",
                    ),
                ),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="health.medication",
                        verbose_name="Medication",
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="health.healthprotocol",
                        verbose_name="Protocol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Protocol Item",
                "verbose_name_plural": "Protocol Items",
                "ordering": ["protocol", "medication__name"],
            },
        ),
    ]
