# Generated by Django 5.2.9 on 2025-12-17 05:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0004_healthprotocol_protocolitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActiveIngredient",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Active Ingredient",
                "verbose_name_plural": "Active Ingredients",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="medication",
            name="active_ingredient",
            field=models.ForeignKey(
                blank=True,
                help_text="Chemical base for compliance grouping.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="medications",
                to="health.activeingredient",
                verbose_name="Active Ingredient",
            ),
        ),
    ]
