# Generated by Django 5.2.9 on 2025-12-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0005_activeingredient_alter_medication_active_ingredient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medication",
            name="active_ingredient",
        ),
        migrations.AddField(
            model_name="medication",
            name="active_ingredients",
            field=models.ManyToManyField(
                blank=True,
                help_text="Chemical bases for compliance grouping.",
                related_name="medications",
                to="health.activeingredient",
                verbose_name="Active Ingredients",
            ),
        ),
    ]
