# Generated by Django 5.2.9 on 2025-12-08 06:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        help_text="CPF/CNPJ",
                        max_length=50,
                        verbose_name="Tax ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Phone"),
                ),
                (
                    "is_customer",
                    models.BooleanField(default=True, verbose_name="Customer"),
                ),
                (
                    "is_supplier",
                    models.BooleanField(default=False, verbose_name="Supplier"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
            ],
            options={
                "verbose_name": "Partner",
                "verbose_name_plural": "Partners",
                "abstract": False,
            },
        ),
    ]
