# Generated by Django 5.2.9 on 2025-12-08 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0001_initial"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Organization",
            new_name="Partner",
        ),
    ]
