# Generated by Django 5.2.9 on 2025-12-18 23:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cattle", "0007_cattle_withdrawal_end_date_alter_cattle_birth_date_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CostEntry",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("NUTRITION", "Nutrition"),
                            ("HEALTH", "Health"),
                            ("REPRODUCTION", "Reproduction"),
                            ("INDIRECT", "Indirect/Overhead"),
                        ],
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Description"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Amount"
                    ),
                ),
                (
                    "object_id",
                    models.UUIDField(blank=True, null=True, verbose_name="Object ID"),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costs",
                        to="cattle.cattle",
                        verbose_name="Animal",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cost Entry",
                "verbose_name_plural": "Cost Entries",
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
    ]
