# Generated by Django 5.2.9 on 2025-12-10 21:16

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cattle", "0005_cattle_current_weight_cattle_last_weighing_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeighingSession",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "date",
                    models.DateField(
                        default=django.db.models.functions.datetime.Now,
                        verbose_name="Date",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Session Name")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Routine"),
                            ("SALE", "Sale"),
                            ("PURCHASE", "Purchase"),
                            ("WEANING", "Weaning"),
                            ("BIRTH", "Birth"),
                        ],
                        default="ROUTINE",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="weighing_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Performed By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Weighing Session",
                "verbose_name_plural": "Weighing Sessions",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WeightRecord",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "weight_kg",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Weight (kg)"
                    ),
                ),
                (
                    "adg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Gain per day since last weighing",
                        max_digits=6,
                        null=True,
                        verbose_name="Average Daily Gain (kg/day)",
                    ),
                ),
                (
                    "days_since_prev_weight",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Days since last weight"
                    ),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weight_records",
                        to="cattle.cattle",
                        verbose_name="Animal",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="weight.weighingsession",
                        verbose_name="Session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Weight Record",
                "verbose_name_plural": "Weight Records",
                "ordering": ["animal__tag"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_deleted", False)),
                        fields=("session", "animal"),
                        name="unique_animal_per_session",
                    )
                ],
            },
        ),
    ]
