# Generated by Django 5.2.9 on 2025-12-21 14:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cattle", "0007_cattle_withdrawal_end_date_alter_cattle_birth_date_and_more"),
        ("partners", "0002_rename_organization_partner"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageTank",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("name", models.CharField(max_length=50, verbose_name="Tank Name")),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Serial Number"
                    ),
                ),
                (
                    "location_description",
                    models.CharField(max_length=100, verbose_name="Physical Location"),
                ),
                (
                    "capacity_liters",
                    models.DecimalField(
                        decimal_places=1, max_digits=5, verbose_name="Capacity (L)"
                    ),
                ),
                (
                    "last_refill_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Last N2 Refill"
                    ),
                ),
            ],
            options={
                "verbose_name": "Storage Tank",
                "verbose_name_plural": "Storage Tanks",
            },
        ),
        migrations.CreateModel(
            name="SemenBatch",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "canister",
                    models.CharField(
                        help_text="e.g. Canister 3, Cane Blue",
                        max_length=50,
                        verbose_name="Canister/Cane",
                    ),
                ),
                (
                    "initial_quantity",
                    models.PositiveIntegerField(verbose_name="Initial Doses/Qty"),
                ),
                (
                    "current_quantity",
                    models.PositiveIntegerField(verbose_name="Current Doses/Qty"),
                ),
                (
                    "min_stock_alert",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Min Stock Alert"
                    ),
                ),
                (
                    "purchase_date",
                    models.DateField(verbose_name="Purchase/Collection Date"),
                ),
                (
                    "cost_per_unit",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Cost per Unit"
                    ),
                ),
                (
                    "bull_name_external",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Bull Name (Ext)"
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(blank=True, max_length=50, verbose_name="RGN"),
                ),
                (
                    "breed",
                    models.CharField(
                        default="Nelore", max_length=50, verbose_name="Breed"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CONVENTIONAL", "Conventional"),
                            ("SEXED_MALE", "Sexed (Male)"),
                            ("SEXED_FEMALE", "Sexed (Female)"),
                        ],
                        default="CONVENTIONAL",
                        max_length=20,
                    ),
                ),
                (
                    "batch_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Batch Code"
                    ),
                ),
                (
                    "bull",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link if the bull is in our system",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="semen_batches",
                        to="cattle.cattle",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="partners.partner",
                        verbose_name="Supplier",
                    ),
                ),
                (
                    "tank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_contents",
                        to="genetics.storagetank",
                    ),
                ),
            ],
            options={
                "verbose_name": "Semen Batch",
                "verbose_name_plural": "Semen Batches",
            },
        ),
        migrations.CreateModel(
            name="EmbryoBatch",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "canister",
                    models.CharField(
                        help_text="e.g. Canister 3, Cane Blue",
                        max_length=50,
                        verbose_name="Canister/Cane",
                    ),
                ),
                (
                    "initial_quantity",
                    models.PositiveIntegerField(verbose_name="Initial Doses/Qty"),
                ),
                (
                    "current_quantity",
                    models.PositiveIntegerField(verbose_name="Current Doses/Qty"),
                ),
                (
                    "min_stock_alert",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Min Stock Alert"
                    ),
                ),
                (
                    "purchase_date",
                    models.DateField(verbose_name="Purchase/Collection Date"),
                ),
                (
                    "cost_per_unit",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Cost per Unit"
                    ),
                ),
                ("sire_name", models.CharField(max_length=100, verbose_name="Sire")),
                ("dam_name", models.CharField(max_length=100, verbose_name="Dam")),
                (
                    "grade",
                    models.CharField(
                        choices=[("1", "Grade 1"), ("2", "Grade 2")],
                        max_length=10,
                        verbose_name="Quality Grade",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        default="Blastocyst", max_length=20, verbose_name="Stage"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="partners.partner",
                        verbose_name="Supplier",
                    ),
                ),
                (
                    "tank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_contents",
                        to="genetics.storagetank",
                    ),
                ),
            ],
            options={
                "verbose_name": "Embryo Batch",
                "verbose_name_plural": "Embryo Batches",
            },
        ),
    ]
