# Generated by Django 5.2.9 on 2025-12-21 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cattle", "0007_cattle_withdrawal_end_date_alter_cattle_birth_date_and_more"),
        ("genetics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="embryobatch",
            name="dam",
            field=models.ForeignKey(
                blank=True,
                help_text="Link if the dam is in our system",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="embryos_dammed",
                to="cattle.cattle",
                verbose_name="Dam (Internal)",
            ),
        ),
        migrations.AddField(
            model_name="embryobatch",
            name="sire",
            field=models.ForeignKey(
                blank=True,
                help_text="Link if the sire is in our system",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="embryos_sired",
                to="cattle.cattle",
                verbose_name="Sire (Internal)",
            ),
        ),
        migrations.AlterField(
            model_name="embryobatch",
            name="dam_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Dam (Ext/Name)"
            ),
        ),
        migrations.AlterField(
            model_name="embryobatch",
            name="sire_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Sire (Ext/Name)"
            ),
        ),
    ]
