# Generated by Django 5.2.9 on 2025-12-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cattle", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cattle",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="cattle_images/",
                verbose_name="Profile Image",
            ),
        ),
    ]
