# Generated by Django 5.2.9 on 2025-12-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cattle", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cattle",
            name="breed",
            field=models.CharField(
                blank=True,
                choices=[
                    ("angus", "Angus"),
                    ("brahman", "Brahman"),
                    ("hereford", "Hereford"),
                    ("holstein", "Holstein"),
                    ("jersey", "Jersey"),
                    ("nelore", "Nelore"),
                    ("simmental", "Simmental"),
                    ("wagyu", "Wagyu"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
                verbose_name="Breed",
            ),
        ),
    ]
