# Generated by Django 5.2.9 on 2025-12-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cattle", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cattle",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Birth Date"),
        ),
        migrations.AlterField(
            model_name="cattle",
            name="weight_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Weight (kg)",
            ),
        ),
    ]
