# Generated by Django 5.2.9 on 2025-12-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cattle", "0002_alter_cattle_birth_date_alter_cattle_weight_kg"),
    ]

    operations = [
        migrations.AddField(
            model_name="cattle",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Name/Nickname of the animal",
                max_length=100,
                verbose_name="Name",
            ),
        ),
    ]
