# Generated by Django 5.2.9 on 2025-12-08 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cattle", "0002_alter_cattle_breed"),
    ]

    operations = [
        migrations.AddField(
            model_name="cattle",
            name="dam",
            field=models.ForeignKey(
                blank=True,
                help_text="Mother, if registered in the herd.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="offspring_dam",
                to="cattle.cattle",
                verbose_name="Dam (Internal)",
            ),
        ),
        migrations.AddField(
            model_name="cattle",
            name="dam_external_id",
            field=models.CharField(
                blank=True,
                help_text="Mother's Name/ID if not in the herd.",
                max_length=100,
                verbose_name="Dam (External ID)",
            ),
        ),
        migrations.AddField(
            model_name="cattle",
            name="electronic_id",
            field=models.CharField(
                blank=True,
                help_text="RFID or EID tag number",
                max_length=100,
                verbose_name="Electronic ID",
            ),
        ),
        migrations.AddField(
            model_name="cattle",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AddField(
            model_name="cattle",
            name="sex",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="female",
                max_length=10,
                verbose_name="Sex",
            ),
        ),
        migrations.AddField(
            model_name="cattle",
            name="sire",
            field=models.ForeignKey(
                blank=True,
                help_text="Father, if registered in the herd.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="offspring_sire",
                to="cattle.cattle",
                verbose_name="Sire (Internal)",
            ),
        ),
        migrations.AddField(
            model_name="cattle",
            name="sire_external_id",
            field=models.CharField(
                blank=True,
                help_text="Father's Name/ID if not in the herd.",
                max_length=100,
                verbose_name="Sire (External ID)",
            ),
        ),
    ]
