# Generated by Django 5.2.9 on 2025-12-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cattle", "0003_cattle_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cattle",
            name="tag",
            field=models.CharField(
                help_text="Ear tag or ID", max_length=50, verbose_name="Tag"
            ),
        ),
        migrations.AddConstraint(
            model_name="cattle",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("tag",),
                name="unique_active_cattle_tag",
            ),
        ),
    ]
