# Generated by Django 5.2.9 on 2025-12-10 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cattle", "0003_cattle_dam_cattle_dam_external_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cattle",
            name="reproduction_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OPEN", "Open"),
                    ("BRED", "Bred"),
                    ("PREGNANT", "Pregnant"),
                    ("LACTATING", "Lactating"),
                ],
                default="OPEN",
                help_text="Biological status of the female.",
                max_length=20,
                verbose_name="Reproduction Status",
            ),
        ),
    ]
