# Generated by Django 5.2.9 on 2025-12-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cattle", "0004_cattle_reproduction_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="cattle",
            name="current_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Current Weight (kg)",
            ),
        ),
        migrations.AddField(
            model_name="cattle",
            name="last_weighing_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Last Weighing Date"
            ),
        ),
    ]
