# Generated by Django 5.2.9 on 2025-12-10 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cattle", "0005_cattle_current_weight_cattle_last_weighing_date"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cattle",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Where the animal is currently located.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cattle",
                to="locations.location",
                verbose_name="Current Location",
            ),
        ),
    ]
