# Generated by Django 5.2.9 on 2025-12-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cattle", "0006_cattle_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="cattle",
            name="withdrawal_end_date",
            field=models.DateField(
                blank=True,
                help_text="Date until which the animal is in withdrawal/withholding period.",
                null=True,
                verbose_name="Withdrawal End Date",
            ),
        ),
        migrations.AlterField(
            model_name="cattle",
            name="birth_date",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="Birth Date"
            ),
        ),
        migrations.AlterField(
            model_name="cattle",
            name="current_weight",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Current Weight (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="cattle",
            name="reproduction_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OPEN", "Open"),
                    ("BRED", "Bred"),
                    ("PREGNANT", "Pregnant"),
                    ("LACTATING", "Lactating"),
                ],
                db_index=True,
                default="OPEN",
                help_text="Biological status of the female.",
                max_length=20,
                verbose_name="Reproduction Status",
            ),
        ),
        migrations.AlterField(
            model_name="cattle",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("sold", "Sold"),
                    ("dead", "Dead"),
                ],
                db_index=True,
                default="available",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
