# Generated by Django 5.2.9 on 2025-12-10 23:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cattle", "0005_cattle_current_weight_cattle_last_weighing_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PASTURE", "Pasture"),
                            ("FEEDLOT", "Feedlot"),
                            ("CORRAL", "Corral"),
                            ("HOSPITAL", "Hospital"),
                            ("MATERNITY", "Maternity"),
                        ],
                        default="PASTURE",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "area_hectares",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Size of the area in hectares",
                        max_digits=10,
                        verbose_name="Area (ha)",
                    ),
                ),
                (
                    "capacity_head",
                    models.PositiveIntegerField(
                        help_text="Maximum recommended animals",
                        verbose_name="Capacity (Head)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="If unchecked, the location is retired or fenced off.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("RESTING", "Resting"),
                            ("MAINTENANCE", "Maintenance"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Movement",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("ROTATION", "Rotation"),
                            ("WEANING", "Weaning"),
                            ("MEDICAL", "Medical Treatment"),
                            ("SALE", "Sale"),
                            ("WEIGHT_CHECK", "Weight Check"),
                            ("OTHER", "Other"),
                        ],
                        default="ROTATION",
                        max_length=20,
                        verbose_name="Reason",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "animals",
                    models.ManyToManyField(
                        related_name="movements",
                        to="cattle.cattle",
                        verbose_name="Animals",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements_in",
                        to="locations.location",
                        verbose_name="Destination",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source location. Null if purchase/entry.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements_out",
                        to="locations.location",
                        verbose_name="Origin",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_performed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Performed By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movement",
                "verbose_name_plural": "Movements",
                "ordering": ["-date"],
            },
        ),
    ]
