# Generated by Django 5.2.9 on 2025-12-20 16:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cattle", "0007_cattle_withdrawal_end_date_alter_cattle_birth_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesEvent",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("name", models.CharField(max_length=100, verbose_name="Event Name")),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "sales_type",
                    models.CharField(
                        choices=[
                            ("AUCTION", "Auction"),
                            ("DIRECT", "Direct Sale"),
                            ("SEMEN", "Semen/Genetics"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Sales Event",
                "verbose_name_plural": "Sales Events",
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SalesLot",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("lot_number", models.PositiveIntegerField(verbose_name="Lot #")),
                (
                    "cost_at_creation",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total Cost Basis"
                    ),
                ),
                (
                    "reserve_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Total Reserve Price",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("SOLD", "Sold"),
                            ("PASSED", "Passed/Unsold"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "animals",
                    models.ManyToManyField(
                        related_name="sales_lots",
                        to="cattle.cattle",
                        verbose_name="Animals",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lots",
                        to="commercial.salesevent",
                        verbose_name="Event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Lot",
                "verbose_name_plural": "Sales Lots",
                "ordering": ["event", "lot_number"],
                "abstract": False,
                "unique_together": {("event", "lot_number")},
            },
        ),
    ]
