# Generated by Django 5.2.9 on 2025-12-21 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cattle", "0007_cattle_withdrawal_end_date_alter_cattle_birth_date_and_more"),
        ("commercial", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleslot",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="saleslot",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="saleslot",
            name="animals",
            field=models.ManyToManyField(
                blank=True,
                related_name="sales_lots",
                to="cattle.cattle",
                verbose_name="Animals",
            ),
        ),
    ]
