# Generated by Django 5.2.9 on 2025-12-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercial", "0002_saleslot_content_type_saleslot_object_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleslot",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Number of items (e.g., doses) in this lot",
                verbose_name="Quantity",
            ),
        ),
    ]
