# Generated by Django 5.2.9 on 2025-12-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commercial", "0003_saleslot_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saleslot",
            name="object_id",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
