# Generated by Django 5.2.9 on 2025-12-10 04:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cattle", "0004_cattle_reproduction_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReproductiveSeason",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Breeding Season 2024/2025",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Reproductive Season",
                "verbose_name_plural": "Reproductive Seasons",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BreedingEvent",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "breeding_method",
                    models.CharField(
                        choices=[
                            ("AI", "Artificial Insemination"),
                            ("IATF", "Fixed-Time AI"),
                            ("NATURAL", "Natural Mating"),
                            ("ET", "Embryo Transfer"),
                        ],
                        default="AI",
                        max_length=20,
                        verbose_name="Method",
                    ),
                ),
                (
                    "sire_name",
                    models.CharField(
                        blank=True,
                        help_text="If sire is not in inventory",
                        max_length=100,
                        verbose_name="Sire Name (External)",
                    ),
                ),
                (
                    "dam",
                    models.ForeignKey(
                        limit_choices_to={"sex": "female"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breeding_events_as_dam",
                        to="cattle.cattle",
                        verbose_name="Dam",
                    ),
                ),
                (
                    "sire",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"sex": "male"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="breeding_events_as_sire",
                        to="cattle.cattle",
                        verbose_name="Sire (Internal)",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="breeding_events",
                        to="reproduction.reproductiveseason",
                        verbose_name="Season/Batch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Breeding Event",
                "verbose_name_plural": "Breeding Events",
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Calving",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("date", models.DateField(verbose_name="Calving Date")),
                (
                    "ease_of_birth",
                    models.CharField(
                        choices=[
                            ("EASY", "Easy/Unassisted"),
                            ("ASSISTED", "Assisted"),
                            ("C_SECTION", "C-Section"),
                        ],
                        default="EASY",
                        max_length=20,
                        verbose_name="Ease of Birth",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "breeding_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calving_outcome",
                        to="reproduction.breedingevent",
                        verbose_name="Linked Breeding Event",
                    ),
                ),
                (
                    "calf",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="birth_event",
                        to="cattle.cattle",
                        verbose_name="Calf",
                    ),
                ),
                (
                    "dam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calvings",
                        to="cattle.cattle",
                        verbose_name="Dam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calving",
                "verbose_name_plural": "Calvings",
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PregnancyCheck",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("date", models.DateField(verbose_name="Check Date")),
                (
                    "result",
                    models.CharField(
                        choices=[("POSITIVE", "Positive"), ("NEGATIVE", "Negative")],
                        max_length=20,
                        verbose_name="Result",
                    ),
                ),
                (
                    "fetus_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Estimated age of fetus in days",
                        null=True,
                        verbose_name="Fetus Days",
                    ),
                ),
                (
                    "expected_calving_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Expected Calving Date"
                    ),
                ),
                (
                    "breeding_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pregnancy_checks",
                        to="reproduction.breedingevent",
                        verbose_name="Breeding Event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pregnancy Check",
                "verbose_name_plural": "Pregnancy Checks",
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
    ]
