# Generated by Django 5.2.9 on 2025-12-10 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reproduction", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reproductiveseason",
            name="active",
        ),
    ]
