# Generated by Django 5.2.9 on 2025-12-18 05:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cattle", "0007_cattle_withdrawal_end_date_alter_cattle_birth_date_and_more"),
        ("reproduction", "0002_remove_reproductiveseason_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatingPlan",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("APPROVED_WAITING", "Approved (Waiting for Location)"),
                            ("ACTIVE", "Active (In Paddock)"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "cows",
                    models.ManyToManyField(
                        limit_choices_to={"sex": "female"},
                        related_name="assigned_mating_plans",
                        to="cattle.cattle",
                        verbose_name="Cows",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mating_plans",
                        to="reproduction.reproductiveseason",
                        verbose_name="Season",
                    ),
                ),
                (
                    "sire",
                    models.ForeignKey(
                        limit_choices_to={"sex": "male"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mating_plans",
                        to="cattle.cattle",
                        verbose_name="Sire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mating Plan",
                "verbose_name_plural": "Mating Plans",
                "ordering": ["-season", "sire__name"],
            },
        ),
        migrations.CreateModel(
            name="MatingExclusion",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("reason", models.CharField(max_length=200, verbose_name="Reason")),
                (
                    "animal_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exclusions_as_a",
                        to="cattle.cattle",
                        verbose_name="Animal A",
                    ),
                ),
                (
                    "animal_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exclusions_as_b",
                        to="cattle.cattle",
                        verbose_name="Animal B",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mating Exclusion",
                "verbose_name_plural": "Mating Exclusions",
                "unique_together": {("animal_a", "animal_b")},
            },
        ),
    ]
